// Liveness fixtures for the descriptor-walk guards: every shape here is a
// planted violation or a planted non-violation the guards_test rows pin.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: powermanage/fixture/v1/fixture.proto

package fixturepb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FixtureBadEnum int32

const (
	// G-2 must flag: zero value is not *_UNSPECIFIED.
	FixtureBadEnum_FIXTURE_BAD_ENUM_ACTIVE FixtureBadEnum = 0
	FixtureBadEnum_FIXTURE_BAD_ENUM_OTHER  FixtureBadEnum = 1
)

// Enum value maps for FixtureBadEnum.
var (
	FixtureBadEnum_name = map[int32]string{
		0: "FIXTURE_BAD_ENUM_ACTIVE",
		1: "FIXTURE_BAD_ENUM_OTHER",
	}
	FixtureBadEnum_value = map[string]int32{
		"FIXTURE_BAD_ENUM_ACTIVE": 0,
		"FIXTURE_BAD_ENUM_OTHER":  1,
	}
)

func (x FixtureBadEnum) Enum() *FixtureBadEnum {
	p := new(FixtureBadEnum)
	*p = x
	return p
}

func (x FixtureBadEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FixtureBadEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_powermanage_fixture_v1_fixture_proto_enumTypes[0].Descriptor()
}

func (FixtureBadEnum) Type() protoreflect.EnumType {
	return &file_powermanage_fixture_v1_fixture_proto_enumTypes[0]
}

func (x FixtureBadEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FixtureBadEnum.Descriptor instead.
func (FixtureBadEnum) EnumDescriptor() ([]byte, []int) {
	return file_powermanage_fixture_v1_fixture_proto_rawDescGZIP(), []int{0}
}

type FixtureGoodEnum int32

const (
	FixtureGoodEnum_FIXTURE_GOOD_ENUM_UNSPECIFIED FixtureGoodEnum = 0
	FixtureGoodEnum_FIXTURE_GOOD_ENUM_ON          FixtureGoodEnum = 1
)

// Enum value maps for FixtureGoodEnum.
var (
	FixtureGoodEnum_name = map[int32]string{
		0: "FIXTURE_GOOD_ENUM_UNSPECIFIED",
		1: "FIXTURE_GOOD_ENUM_ON",
	}
	FixtureGoodEnum_value = map[string]int32{
		"FIXTURE_GOOD_ENUM_UNSPECIFIED": 0,
		"FIXTURE_GOOD_ENUM_ON":          1,
	}
)

func (x FixtureGoodEnum) Enum() *FixtureGoodEnum {
	p := new(FixtureGoodEnum)
	*p = x
	return p
}

func (x FixtureGoodEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FixtureGoodEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_powermanage_fixture_v1_fixture_proto_enumTypes[1].Descriptor()
}

func (FixtureGoodEnum) Type() protoreflect.EnumType {
	return &file_powermanage_fixture_v1_fixture_proto_enumTypes[1]
}

func (x FixtureGoodEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FixtureGoodEnum.Descriptor instead.
func (FixtureGoodEnum) EnumDescriptor() ([]byte, []int) {
	return file_powermanage_fixture_v1_fixture_proto_rawDescGZIP(), []int{1}
}

type FixtureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// G-1 must flag: reachable boundary field with no validate rules.
	UntaggedName string `protobuf:"bytes,1,opt,name=untagged_name,json=untaggedName,proto3" json:"untagged_name,omitempty"`
	// G-1 must not flag.
	TaggedId string `protobuf:"bytes,2,opt,name=tagged_id,json=taggedId,proto3" json:"tagged_id,omitempty"`
	// Reachability hop: NestedParams joins the boundary through this field.
	Nested *NestedParams `protobuf:"bytes,3,opt,name=nested,proto3" json:"nested,omitempty"`
	// Foreign well-known type: reachable through this (tagged) field, but its
	// internal fields are not contract surface — the closure must not walk
	// into messages defined outside the audited files.
	StampedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=stamped_at,json=stampedAt,proto3" json:"stamped_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixtureRequest) Reset() {
	*x = FixtureRequest{}
	mi := &file_powermanage_fixture_v1_fixture_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixtureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixtureRequest) ProtoMessage() {}

func (x *FixtureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_powermanage_fixture_v1_fixture_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixtureRequest.ProtoReflect.Descriptor instead.
func (*FixtureRequest) Descriptor() ([]byte, []int) {
	return file_powermanage_fixture_v1_fixture_proto_rawDescGZIP(), []int{0}
}

func (x *FixtureRequest) GetUntaggedName() string {
	if x != nil {
		return x.UntaggedName
	}
	return ""
}

func (x *FixtureRequest) GetTaggedId() string {
	if x != nil {
		return x.TaggedId
	}
	return ""
}

func (x *FixtureRequest) GetNested() *NestedParams {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *FixtureRequest) GetStampedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StampedAt
	}
	return nil
}

type NestedParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// G-1 must flag THROUGH the closure — a nested message is boundary too.
	UntaggedInner string `protobuf:"bytes,1,opt,name=untagged_inner,json=untaggedInner,proto3" json:"untagged_inner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedParams) Reset() {
	*x = NestedParams{}
	mi := &file_powermanage_fixture_v1_fixture_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedParams) ProtoMessage() {}

func (x *NestedParams) ProtoReflect() protoreflect.Message {
	mi := &file_powermanage_fixture_v1_fixture_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedParams.ProtoReflect.Descriptor instead.
func (*NestedParams) Descriptor() ([]byte, []int) {
	return file_powermanage_fixture_v1_fixture_proto_rawDescGZIP(), []int{1}
}

func (x *NestedParams) GetUntaggedInner() string {
	if x != nil {
		return x.UntaggedInner
	}
	return ""
}

type FixtureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaggedOut     string                 `protobuf:"bytes,1,opt,name=tagged_out,json=taggedOut,proto3" json:"tagged_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixtureResponse) Reset() {
	*x = FixtureResponse{}
	mi := &file_powermanage_fixture_v1_fixture_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixtureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixtureResponse) ProtoMessage() {}

func (x *FixtureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_powermanage_fixture_v1_fixture_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixtureResponse.ProtoReflect.Descriptor instead.
func (*FixtureResponse) Descriptor() ([]byte, []int) {
	return file_powermanage_fixture_v1_fixture_proto_rawDescGZIP(), []int{2}
}

func (x *FixtureResponse) GetTaggedOut() string {
	if x != nil {
		return x.TaggedOut
	}
	return ""
}

type UnreachableLoose struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Declared but not service-reachable: G-1 must NOT flag it.
	NeverFlagged  string `protobuf:"bytes,1,opt,name=never_flagged,json=neverFlagged,proto3" json:"never_flagged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnreachableLoose) Reset() {
	*x = UnreachableLoose{}
	mi := &file_powermanage_fixture_v1_fixture_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreachableLoose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreachableLoose) ProtoMessage() {}

func (x *UnreachableLoose) ProtoReflect() protoreflect.Message {
	mi := &file_powermanage_fixture_v1_fixture_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreachableLoose.ProtoReflect.Descriptor instead.
func (*UnreachableLoose) Descriptor() ([]byte, []int) {
	return file_powermanage_fixture_v1_fixture_proto_rawDescGZIP(), []int{3}
}

func (x *UnreachableLoose) GetNeverFlagged() string {
	if x != nil {
		return x.NeverFlagged
	}
	return ""
}

var File_powermanage_fixture_v1_fixture_proto protoreflect.FileDescriptor

const file_powermanage_fixture_v1_fixture_proto_rawDesc = "" +
	"\n" +
	"$powermanage/fixture/v1/fixture.proto\x12\x16powermanage.fixture.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe5\x01\n" +
	"\x0eFixtureRequest\x12#\n" +
	"\runtagged_name\x18\x01 \x01(\tR\funtaggedName\x12%\n" +
	"\ttagged_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\btaggedId\x12D\n" +
	"\x06nested\x18\x03 \x01(\v2$.powermanage.fixture.v1.NestedParamsB\x06\xbaH\x03\xc8\x01\x01R\x06nested\x12A\n" +
	"\n" +
	"stamped_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tstampedAt\"5\n" +
	"\fNestedParams\x12%\n" +
	"\x0euntagged_inner\x18\x01 \x01(\tR\runtaggedInner\"9\n" +
	"\x0fFixtureResponse\x12&\n" +
	"\n" +
	"tagged_out\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\ttaggedOut\"7\n" +
	"\x10UnreachableLoose\x12#\n" +
	"\rnever_flagged\x18\x01 \x01(\tR\fneverFlagged*I\n" +
	"\x0eFixtureBadEnum\x12\x1b\n" +
	"\x17FIXTURE_BAD_ENUM_ACTIVE\x10\x00\x12\x1a\n" +
	"\x16FIXTURE_BAD_ENUM_OTHER\x10\x01*N\n" +
	"\x0fFixtureGoodEnum\x12!\n" +
	"\x1dFIXTURE_GOOD_ENUM_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14FIXTURE_GOOD_ENUM_ON\x10\x012g\n" +
	"\x0eFixtureService\x12U\n" +
	"\x02Do\x12&.powermanage.fixture.v1.FixtureRequest\x1a'.powermanage.fixture.v1.FixtureResponseBjZhgithub.com/manchtools/power-manage/contract/archtest/internal/fixturepb/powermanage/fixture/v1;fixturepbb\x06proto3"

var (
	file_powermanage_fixture_v1_fixture_proto_rawDescOnce sync.Once
	file_powermanage_fixture_v1_fixture_proto_rawDescData []byte
)

func file_powermanage_fixture_v1_fixture_proto_rawDescGZIP() []byte {
	file_powermanage_fixture_v1_fixture_proto_rawDescOnce.Do(func() {
		file_powermanage_fixture_v1_fixture_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_powermanage_fixture_v1_fixture_proto_rawDesc), len(file_powermanage_fixture_v1_fixture_proto_rawDesc)))
	})
	return file_powermanage_fixture_v1_fixture_proto_rawDescData
}

var file_powermanage_fixture_v1_fixture_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_powermanage_fixture_v1_fixture_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_powermanage_fixture_v1_fixture_proto_goTypes = []any{
	(FixtureBadEnum)(0),           // 0: powermanage.fixture.v1.FixtureBadEnum
	(FixtureGoodEnum)(0),          // 1: powermanage.fixture.v1.FixtureGoodEnum
	(*FixtureRequest)(nil),        // 2: powermanage.fixture.v1.FixtureRequest
	(*NestedParams)(nil),          // 3: powermanage.fixture.v1.NestedParams
	(*FixtureResponse)(nil),       // 4: powermanage.fixture.v1.FixtureResponse
	(*UnreachableLoose)(nil),      // 5: powermanage.fixture.v1.UnreachableLoose
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_powermanage_fixture_v1_fixture_proto_depIdxs = []int32{
	3, // 0: powermanage.fixture.v1.FixtureRequest.nested:type_name -> powermanage.fixture.v1.NestedParams
	6, // 1: powermanage.fixture.v1.FixtureRequest.stamped_at:type_name -> google.protobuf.Timestamp
	2, // 2: powermanage.fixture.v1.FixtureService.Do:input_type -> powermanage.fixture.v1.FixtureRequest
	4, // 3: powermanage.fixture.v1.FixtureService.Do:output_type -> powermanage.fixture.v1.FixtureResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_powermanage_fixture_v1_fixture_proto_init() }
func file_powermanage_fixture_v1_fixture_proto_init() {
	if File_powermanage_fixture_v1_fixture_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_powermanage_fixture_v1_fixture_proto_rawDesc), len(file_powermanage_fixture_v1_fixture_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_powermanage_fixture_v1_fixture_proto_goTypes,
		DependencyIndexes: file_powermanage_fixture_v1_fixture_proto_depIdxs,
		EnumInfos:         file_powermanage_fixture_v1_fixture_proto_enumTypes,
		MessageInfos:      file_powermanage_fixture_v1_fixture_proto_msgTypes,
	}.Build()
	File_powermanage_fixture_v1_fixture_proto = out.File
	file_powermanage_fixture_v1_fixture_proto_goTypes = nil
	file_powermanage_fixture_v1_fixture_proto_depIdxs = nil
}
