#!/usr/bin/env bash
# CI conventions check (SPEC-002 AC-8, G-002-8): conventional commits
# [VER-2], vYYYY.MM.PP tag format [VER-1], no AI attribution [META-4].
# Modes keep the script runnable against fixture repos offline; the
# workflow passes GitHub context in. This file names the attribution
# patterns and is exempt from check-self-contained.sh for that reason.
set -u -o pipefail

SUBJECT_RE='^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z0-9._/-]+\))?!?: .+'
TAG_RE='^v20[0-9]{2}\.(0[1-9]|1[0-2])\.[0-9]{2}$'
# Test-owned threat model — red/green rows live in
# check-conventions_test.sh; file CONTENTS stay check-self-contained.sh's
# job, this covers commit messages and PR bodies.
# Literal tokens, matched case-insensitively: the canonical git trailer
# is "Co-authored-by", hosts and addresses are case-insensitive, and a
# casing variant must not evade [META-4].
ATTR_PATTERNS_CI=(
  'Co-Authored-By'
  'noreply@anthropic\.com'
  'claude\.com/claude-code'
  '🤖'
)
# Case-sensitive: the Capital after "generated with/by" is load-bearing.
# Deliberately broad — any Capitalized tool, so a new AI vendor cannot
# slip through a name allowlist. Ceiling: a body like "Regenerated with
# Buf" is rejected too and must be reworded; that false positive fails
# CLOSED. Lowercase tool mentions ("generated by protoc-gen-go") stay
# clean; green row in the self-test.
ATTR_PATTERNS_CS=(
  '[Gg]enerated (with|by) [A-Z]'
)

fail=0

attr_match() { # attr_match <label> <text> <grep args ending in pattern...>
  local label="$1" text="$2" rc
  shift 2
  grep -q "$@" <<<"$text"
  rc=$?
  if [ "$rc" -eq 0 ]; then
    echo "conventions: $label carries attribution (pattern: ${*: -1}) [META-4]"
    fail=1
  elif [ "$rc" -gt 1 ]; then
    # Conflating "grep broke" with "clean" would make this check fail open.
    echo "conventions: GUARD ERROR — grep exited $rc on pattern ${*: -1}"
    fail=1
  fi
}

check_attribution() { # check_attribution <label> <text>
  local p
  for p in "${ATTR_PATTERNS_CI[@]}"; do
    attr_match "$1" "$2" -iE "$p"
  done
  for p in "${ATTR_PATTERNS_CS[@]}"; do
    attr_match "$1" "$2" -E "$p"
  done
}

mode="${1:-}"
case "$mode" in
  commits)
    range="${2:?usage: check-conventions.sh commits <range>}"
    mapfile -t shas < <(git rev-list --no-merges "$range")
    if [ "${#shas[@]}" -eq 0 ]; then
      echo "conventions: zero commits examined in range $range — the lint must see at least one commit (G-002-8)"
      exit 1
    fi
    for sha in "${shas[@]}"; do
      subject=$(git log -1 --format=%s "$sha")
      if ! grep -qE "$SUBJECT_RE" <<<"$subject"; then
        echo "conventions: commit ${sha:0:7} subject is not a conventional commit [VER-2]: $subject"
        fail=1
      fi
      check_attribution "commit ${sha:0:7}" "$(git log -1 --format=%B "$sha")"
    done
    ;;
  ci-commits)
    # Workflow entry: resolve the examined range from GitHub context.
    # An empty or unknown base (first/forced push) falls back to the
    # head commit alone — still ≥1 commit examined, never zero.
    base="${2:-}"
    head="${3:?usage: check-conventions.sh ci-commits <base> <head>}"
    if [ -z "$base" ] || ! git cat-file -e "$base" 2>/dev/null; then
      if ! git cat-file -e "$head~1" 2>/dev/null; then
        # Parentless head (a repo's first push): rev-list <head> is
        # exactly that one commit — still ≥1 examined, never zero.
        exec "$0" commits "$head"
      fi
      exec "$0" commits "$head~1..$head"
    fi
    exec "$0" commits "$base..$head"
    ;;
  pr-body-file)
    f="${2:?usage: check-conventions.sh pr-body-file <file>}"
    if [ ! -r "$f" ]; then
      echo "conventions: PR body file $f is not readable — refusing to pass an unchecked body"
      exit 1
    fi
    check_attribution "PR body" "$(cat "$f")"
    ;;
  tag)
    t="${2:?usage: check-conventions.sh tag <name>}"
    if ! grep -qE "$TAG_RE" <<<"$t"; then
      echo "conventions: tag $t does not match vYYYY.MM.PP [VER-1]"
      fail=1
    fi
    ;;
  *)
    echo "usage: check-conventions.sh commits <range> | ci-commits <base> <head> | pr-body-file <file> | tag <name>"
    exit 2
    ;;
esac

if [ "$fail" -eq 0 ]; then
  echo "conventions: OK"
fi
exit "$fail"
